### ISSUE TITLE
DSL specification link is out of date

### ISSUE THREAD

**Issue by webmaven** [cloudify-cosmo/cloudify-dsl-parser#76]
The README contains the link `http://getcloudify.org/guide/dsl-spec-general.html`, this redirects to `http://getcloudify.orghttp//docs.getcloudify.org/dsl-spec-general.html`, which is broken (probably due to a bad redirect rule), but even the (I am guessing) intended url `http://docs.getcloudify.org/dsl-spec-general.html` 404s, although `http://getcloudify.org/guide/3.2/dsl-spec-general.html' works.

Is the current correct URL supposed to be `http://docs.getcloudify.org/3.3.1/blueprints/spec-dsl-definitions/', or something else?

**Comment by kgoedecke** [comment]
this seems to occur on so many of the Cloudify README files, +1 to clean all this dead stuff up!

**Comment by webmaven** [comment]
@max-orlov @dankilman @idanmo, can you answer my Q above?

**Comment by idanmo** [comment]
Hi!

Please use this link: http://docs.getcloudify.org/3.3.1/blueprints/overview/
Indeed all the dead stuff should be cleaned!

Thanks!

**Comment by webmaven** [comment]
The link in the README still redirects to a 404.
